### ISSUE TITLE
KeyError: 'filenames'

### ISSUE THREAD

**Issue by jgrean81** [JonathanFly/3d-ken-burns#8]
```
Not sure what this means
Traceback (most recent call last):
  File "fullrez.py", line 7, in <module>
    import cupy
  File "/usr/local/lib/python3.7/dist-packages/cupy/__init__.py", line 12, in <module>
    _environment._preload_libraries()  # NOQA
  File "/usr/local/lib/python3.7/dist-packages/cupy/_environment.py", line 307, in _preload_libraries
    filenames = config[lib]['filenames']
KeyError: 'filenames'
```

Was looking at testing this for viability on a doco, eventually aiming to have something local running here.
We hoped to test on something that wasn't a small, highly compressed MP4 to see what kind of quality, so had high hopes for this high-res test we found.
Any chance you can point us in the right direction to make this work?
Cheers
JG

**Comment by jgrean81** [comment]
Happens on test as well as fullres.

Traceback (most recent call last):
  File "fullrez.py", line 7, in <module>
    import cupy
  File "/usr/local/lib/python3.7/dist-packages/cupy/__init__.py", line 12, in <module>
    _environment._preload_libraries()  # NOQA
  File "/usr/local/lib/python3.7/dist-packages/cupy/_environment.py", line 307, in _preload_libraries
    filenames = config[lib]['filenames']
KeyError: 'filenames'
